title: Ella Gainey 
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
#logo: "https://user-images.githubusercontent.com/63382246/118050943-08f75e80-b335-11eb-9f59-b71ba5072269.JPG"


description: > 
  Bachelors of Science from University of Washington in Computer Science - graduated March 2021. 
  <br><br>
  Currently looking for entry level software engineer positions.  
  <br><br>
  <a href="https://www.linkedin.com/in/ella-gainey/">View My LinkedIn Profile</a> 
  
#theme: jekyll-theme-minimal
remote_theme: pages-themes/architect@v0.2.0
