title: Ella Gainey 
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
#logo: "https://user-images.githubusercontent.com/63382246/118050943-08f75e80-b335-11eb-9f59-b71ba5072269.JPG"


description: > 
  Software Developer 
  <br><br>
  
#theme: jekyll-theme-minimal
remote_theme: pages-themes/architect@v0.2.0
