title: Ella Gainey 
#logo: "/images/logo.png?raw=true" # your photo (or logo) here
logo: "https://user-images.githubusercontent.com/63382246/82266923-ded8af80-991f-11ea-929a-911903a9b40e.jpg"

description: > 
  Computer Science student at University of Washington Tacoma. 
  <br><br>
  Expected graduation is March 2021. 
  <br><br>
  <a href="www.linkedin.com/in/ella-gainey">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
